### ISSUE TITLE
Store custom image `request_hash` in url

### ISSUE THREAD

**Issue by aparcar** [mwarning/openwrt-firmware-selector#17]
Since https://github.com/aparcar/asu/commit/903a264436054b7563a790202d48a2d0bbcb21c4 it is possible to directly request images hashes. Each time an image is created an anchor should be set to make links shareable. 

If YAFS detects an anchor it should request the image information via `/api/build/<request_hash>`.

**Comment by mwarning** [comment]
Why not send the URL with the hash in the first place?

**Comment by mwarning** [comment]
Is this feature implemented?

**Comment by mwarning** [comment]
not applicable anymore
