### ISSUE TITLE
Feature: give URL to install-instructions

### ISSUE THREAD

**Issue by Akira25** [mwarning/openwrt-firmware-selector#62]
It would be really cool, if there was a link to the install-instructions in ones routers wiki-page. Thus one could get special information and hints for pitfalls in installation process easily. I consider this a very handy feature for everyone flashing different types of routers often.

**Comment by mwarning** [comment]
This feature is now available in the configuration file (`config.js`). Just uncomment the `info_url` setting. It will include a link into openwrt wiki search. It is not ideal. Hopefully the wiki will be able to provide a uniform way to link to model sites.
