### ISSUE TITLE
minor stuff: Version number wasn't increased

### ISSUE THREAD

**Issue by Akira25** [mwarning/openwrt-firmware-selector#74]
In the last release the actual release number wasn't increased in the html code.

https://github.com/mwarning/openwrt-firmware-selector/blob/f44196e1e7b3748b0d8fc796e2c3be1f45fdd33f/www/index.html#L151

**Comment by mwarning** [comment]
hah, you are right. I will fix that with some force.

**Comment by mwarning** [comment]
fixed, thanks
