### ISSUE TITLE
Problem with searching model

### ISSUE THREAD

**Issue by obsy** [mwarning/openwrt-firmware-selector#76]
Very strange issue. Example: https://mwarning.github.io/openwrt-firmware-selector/www/?version=SNAPSHOT&target=ramips%2Fmt76x8&id=hilink_hlk-7628n
 
- if you search hilink hlk-7627n (lowercase, write by hand) - works
- if you search HLK-7628N (capitalcase, write by hand) - works
- but if you search HILINK HLK-7628N (capitalcase, with space - write by hand) - No model found!
- if you search HILINK HLK-7628n (capitalcase, with space, last lowercase - write by hand) - works

Tested on chrome (linux) and edge (linux).

**Comment by mwarning** [comment]
This edge case should be fixed by this: https://gitlab.com/openwrt/web/firmware-selector-openwrt-org/-/merge_requests/86 (will also be applied in this repo)

**Comment by mwarning** [comment]
Added now. Please test if this fixes your issue.

**Comment by obsy** [comment]
Yes and no :). If you type HILINK HLK7628N - this opens device. But if you type HILINK HLK7628n (lowercase last letter) - it will stay in the list and need to be clicked manually.

**Comment by mwarning** [comment]
`HILINK HLK7628n` isn't a perfect match. So then the select list should open. No? :)

**Comment by obsy** [comment]
No. Perfect match on 19.07.5 :)

**Comment by mwarning** [comment]
![match](https://user-images.githubusercontent.com/546193/155854580-873208f6-2835-4bb7-ad70-bfb2ce2a3743.png)

Looks good to me.

**Comment by obsy** [comment]
Ah, ok, so it respect uppercase and lowercase in names. In this case - it is ok.

**Comment by mwarning** [comment]
yes, we are a bit picky here about what a perfect match is.
